config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
             controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :feedbacks, only: %i[new create], shallow: true

  resources :badges, only: %i[index]

  get '/collection', to: 'badges#collection'

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
    resources :gists, only: %i[new create], shallow: true
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/admin.rb
class Admin < User

  validates :first_name, presence: true
  validates :last_name, presence: true

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :answer_limit, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def answer_limit
    errors.add(:answer_limit) if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord

  RULE = %w[category first_attempt level].freeze

  has_many :users, through: :user_badges
  has_many :user_badges, dependent: :destroy

end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(:title) }

  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/models/feedback.rb
class Feedback < ApplicationRecord

  validates :name,  presence: true
  validates :email, presence: true
  validates :message,  presence: true

end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :url, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists
  has_many :test_passages, foreign_key: :current_question_id, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User'

  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  scope :easy_level, -> { where(level: 0..1) }
  scope :medium_level, -> { where(level: 2..4) }
  scope :hard_level, -> { where(level: 5..Float::INFINITY) }

  scope :passed_test, -> { includes(:test_passages).where('success_percent >= ?', TestPassage::SUCCESS_RATE) }
  scope :by_category, ->(category) { joins(:category).where('categories.title = ?', category) }
  scope :by_level, ->(level) { where('level = ?', level) }

  validates :title, presence: true,
            uniqueness: { scope: :level,
                          message: 'title and level must be unique'}
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.find_test_by_category(name_category)
    joins(:category)
      .where(categories: { title: name_category })
      .order(:title)
      .pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_current_question

  SUCCESS_RATE = 85

  def completed?
    current_question.nil? || time_out?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids) && time_alive?
      self.correct_questions += 1
      self.success_percent = result
    end

    save!
  end

  def success?
    result >= SUCCESS_RATE
  end

  def time_out?
    test.timer? && timer_finish.past?
  end

  def time_alive?
    !time_out?
  end

  def result
    ((self.correct_questions).to_f / (question_count) * 100).round
  end

  def current_question_number
    test.questions.order(:id).where('id < ?', current_question.id).size + 1
  end

  def question_count
    test.questions.count
  end

  def timer_finish
    created_at + test.timer.minutes
  end

  private

  def set_current_question
    self.current_question = next_question
  end

  def next_question
    if test.present? && current_question.nil?
      test.questions.first
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == Array(answer_ids).map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :user_badges
  has_many :badges, through: :user_badges
  has_many :author_test, class_name: 'Test', foreign_key: :author_id
  has_many :gists

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL = URI::MailTo::EMAIL_REGEXP
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL },
            uniqueness: true

  def level_test(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :badge
  belongs_to :user
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController

  before_action :find_test_passage, only: :create

  def create
    result = GistQuestionService.new(@test_passage.current_question).call

    if result.success?
      current_user.gists.create(question: @test_passage.current_question, url: result.gist_url)

      flash_options = { notice: t('.success', url_html: helpers.link_to(result.gist_url, result.gist_url, target: '_blank').html_safe) }
    else
      flash_options = { alert: t('.failure') }
    end

    redirect_to @test_passage, flash_options
  end

  private

  def find_test_passage
    @test_passage = TestPassage.find(params[:test_passage_id])
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  before_action :authenticate_user!, except: %i[index]
  before_action :set_test, only: %i[start]

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def set_test
    @test = Test.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.current.year
  end

  def github(user, repo)
    link_to user, "https://github.com/#{user}/#{repo}", target: '_blank'
  end

  def flash_messages
    content_tag :div do
      flash.each do |key, message|
        concat content_tag(:div, message.html_safe, class: "alert alert-#{flash_class(key)}", role: 'notice')
      end
    end
  end

  def flash_class(level)
    case level
    when :notice then "info"
    when :success then "success"
    when :error then "error"
    end
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create New #{question.test.title} Question"
    else
      "Edit #{question.test.title} Question"
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper

  TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard }.freeze

  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_nav.html.erb
<nav class="navbar" style="background-color: #938cef;">
  <div class="container-fluid">
    <span class="navbar-text">
      <%= link_to 'TestGuru', root_path%> <%= t('.admin_panel') %>
    </span>
    <div class="nav-admin user">
      <% if current_user.is_a?(Admin) %>
        <span class="badge rounded-pill text-bg-info"><%= link_to 'Adminpanel', admin_tests_path %></span>
      <% end %>
      <%= t('.header') %> <b class="nav-admin user-email"><%= current_user.email %>!</b> Guru |
      <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
    </div>
  </div>
</nav>

app/views/layouts/_footer.html.erb
<style>
  footer {
      padding: 10px 20px;
      background: #999;
      color: white;
  }
</style>

<footer>
  <p>Текущий год: <%= Time.now.strftime("%Y") %></p>
  <address>Автор: Буянов Антон</address>
  Приложение TestGuru позволяет создавать, редактировать и выполнять различные тесты.<br>
  <a href ="https://thinknetica.com" target="_blank" rel="nofollow noopener">
    Учебный проект в онлайн-школе Thinknetica
  </a>
</footer>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Panel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/nav' %>

    <%= render 'shared/flash' %>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>

    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
  </body>
  <%= render 'shared/footer' %>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2>
      <%= t('.header', count: resource.errors.count) %>:
    </h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<%= flash_messages %>

app/views/shared/_footer.html.erb
<style>
  footer {
      padding: 10px 20px;
      background: #999;
      color: white;
  }
</style>
<%= link_to 'Обратная связь', new_feedback_path %>
<footer>
  <p>Текущий год: <%= current_year %></p>
  <address>Автор: <%= github("AntonBuyanov", "TestGuru") %> </address>
  Приложение TestGuru позволяет создавать, редактировать и проходить различные тесты.<br>
  <a href ="https://thinknetica.com" target="_blank" rel="nofollow noopener">
    Учебный проект в онлайн-школе Thinknetica
  </a>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-success" style="background-color: #F1EFEF;">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>

  <span class="navbar-text">
    <% if current_user.is_a?(Admin) %>
        <span class="badge rounded-pill text-bg-info"><%= link_to 'AdminPanel', admin_tests_path %></span>
    <% end %>
    <% if user_signed_in? %>
      <%= t('.welcome') %> <b><%= current_user.email %></b> Guru |
      <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to t('.login'), new_user_session_path %> |
      <%= link_to t('.signup'), new_user_registration_path %>
    <% end %>
  </span>
</nav>

app/views/shared/_progress_bar.html.erb
<div class="progress">
  <%= content_tag :div, "Вопрос #{@test_passage.current_question_number} из #{@test_passage.question_count}",
                  class: "progress-bar progress-bar-striped progress-bar-animated bg-info",
                  role: "progressbar",
                  data: { question_number: @test_passage.current_question_number,
                          question_count: @test_passage.question_count},
                  'aria_valuemin': '0',
                  'aria_valuemax': '100'%>
</div>

app/views/shared/_timer.html.erb
<%= content_tag :div, nil,
                class: 'countdown',
                data: { timer: @test_passage.timer_finish.to_s }
                %>