config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
             controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :feedbacks, only: %i[new create], shallow: true

  resources :badges, only: %i[index]

  get '/collection', to: 'badges#collection'

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
    resources :gists, only: %i[new create], shallow: true
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists
  has_many :test_passages, foreign_key: :current_question_id, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_current_question

  SUCCESS_RATE = 85

  def completed?
    current_question.nil? || time_out?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids) && time_alive?
      self.correct_questions += 1
      self.success_percent = result
    end

    save!
  end

  def success?
    result >= SUCCESS_RATE
  end

  def time_out?
    test.timer? && timer_finish.past?
  end

  def time_alive?
    !time_out?
  end

  def result
    ((self.correct_questions).to_f / (question_count) * 100).round
  end

  def current_question_number
    test.questions.order(:id).where('id < ?', current_question.id).size + 1
  end

  def question_count
    test.questions.count
  end

  def timer_finish
    created_at + test.timer.minutes
  end

  private

  def set_current_question
    self.current_question = next_question
  end

  def next_question
    if test.present? && current_question.nil?
      test.questions.first
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == Array(answer_ids).map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result]

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      BadgeTestService.new(@test_passage).call if @test_passage.success?
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def result_message(test_passages)
    test_passages.success? ? 'Тест пройден' : 'Тест не пройден'
  end

  def result_style(test_passages)
    test_passages.success? ? 'color:green' : 'color:red'
  end
end

app/views/test_passages/result.html.erb
<h3><%= result_message(@test_passage) %>
<strong style=<%= result_style(@test_passage) %>>
  <%= @test_passage.result %>%</strong></h3>
Правильных ответов: <%= @test_passage.correct_questions %></br>
<%= link_to 'Вернуться к списку тестов', tests_path %>

app/views/test_passages/show.html.erb
<h1><%= t('.passage') %> <%= @test_passage.test.title %> <%= t('.test') %></h1>
<%= render 'shared/progress_bar' %>
<% if @test_passage.test.timer %>
  <%= render 'shared/timer' %>
<% end %>

<p class="lead">
  <%= @test_passage.current_question.body %>
</p>

<div class="card card-body mb-3">
  <%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
    <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
     <div class="form-check">
       <p>
         <%= b.check_box id: "answer_ids_#{b.object.id}", class: 'form-check-input' %>
         <%= b.label class: 'form-check-label' %>
       </p>
     </div>
    <% end %>

    <p><%= link_to 'Gist Question', test_passage_gists_path(@test_passage), method: :post %></p>
    <p><%= form.submit t('.next'), class: 'btn btn-primary' %></p>
  <% end %>
</div>