config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
             controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :feedbacks, only: %i[new create], shallow: true

  resources :badges, only: %i[index]

  get '/collection', to: 'badges#collection'

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
    resources :gists, only: %i[new create], shallow: true
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :answer_limit, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def answer_limit
    errors.add(:answer_limit) if question.answers.count >= 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController

  before_action :find_question, only: %i[new create]
  before_action :set_answer, only: %i[show edit update destroy]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit
  end

  def create
    @answer = @question.answers.build(answer_params)

    if @answer.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_question_path(@answer.question)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question)
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.body %>
  <% if answer.correct? %>
    ✓
  <% end %>
  <p>
    <%= link_to t('.show'), admin_answer_path(answer), class: 'btn btn-outline-primary btn-sm' %>
    <%= link_to t('.edit'), edit_admin_answer_path(answer), class: 'btn btn-outline-primary btn-sm' %>
    <%= link_to t('.delete'),
                admin_answer_path(answer), class: 'btn btn-outline-primary btn-sm',
                method: :delete,
                data: { confirm: t('admin.tests.show.sure') }%>
  </p>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.text_area :body, id: :answer_body, autofocus: true, class: 'form-control' %>
  </p>

  <div class="form-check">
    <%= form.label :correct, class: 'form-check-label' do %>
      <%= form.check_box :correct, class: 'form-check-input' %>
      <%= t('admin.answers.correct')  %>
    <% end %>
  </div>

  <p><%= form.submit class: 'btn btn-primary mt-1' %></p>
<% end %>

app/views/admin/answers/edit.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-4">
    <h1><%= t('.edit_answer') %></h1>

    <p>
      <%= @answer.question.body %>
    </p>

    <%= render 'form' %>
    <%= link_to t('.back'), admin_question_path(@answer.question) %>
  </div>
</div>

app/views/admin/answers/new.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-4">
    <h1><%= t('.new_answer') %></h1>

    <p>
      <%= @question.body %>
    </p>

    <%= render 'form' %>
    <%= link_to t('.back'), admin_question_path(@question) %>
  </div>
</div>

app/views/admin/answers/show.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-8">
    <h5><%= t('.question') %></h5>

    <p>
      <%= @answer.question.body %>
    </p>

    <p>
      <b><%= t('.answer') %></b>
      <%= @answer.body %>
    </p>

    <p>
      <b><%= t('.correct') %></b>
      <%= @answer.correct %>
    </p>

    <%= link_to t('.back'), admin_question_path(@answer.question) %>
  </div>
</div>