config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
             controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :feedbacks, only: %i[new create], shallow: true

  resources :badges, only: %i[index]

  get '/collection', to: 'badges#collection'

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
    resources :gists, only: %i[new create], shallow: true
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists
  has_many :test_passages, foreign_key: :current_question_id, dependent: :destroy

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController

  before_action :find_question, only: %i[show destroy edit update]
  before_action :find_test, only: %i[new create]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def show; end

  def new
    @question = @test.questions.new
  end

  def edit; end

  def create
    @question = @test.questions.new(question_params)

    if @question.save
      redirect_to admin_test_path(@test)
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to admin_test_path(@question.test)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy

    redirect_to admin_test_path(@question.test)
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: 'Question was not found'
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create New #{question.test.title} Question"
    else
      "Edit #{question.test.title} Question"
    end
  end
end

app/views/admin/questions/_form.html.erb
<div class="card">
  <div class="card-body">
    <%= form_with model: [:admin, @test, @question], local: true do |form| %>
      <%= render 'shared/errors', resource: @question %>
      <div class="form-group">
      <p>
        <%= form.text_field :body, id: :question_body, autofocus: true, class: 'form-control' %>
      </p><br>

      <p><%= form.submit class: 'btn btn-primary mt-1' %></p>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/questions/_question.html.erb
<li>
  <%= question.body %><br>
  <%= link_to t('.show'), admin_question_path(answer) %>
  <%= link_to t('.edit'), edit_admin_question_path(answer) %>
  <%= link_to t('.delete'),
              admin_question_path(question),
              method: :delete,
              data: { confirm: t('admin.tests.show.sure') }%>
</li>

app/views/admin/questions/edit.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-4">
    <h1> <%= t('.edit') %> </h1>
    <%= render 'form' %>

    <%= link_to t('.back'), admin_test_path(@question.test) %>
  </div>
</div>

app/views/admin/questions/new.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-4">
    <h1><%= t('.new_question') %></h1>

    <%= render 'form' %>

    <%= link_to t('.back'), admin_test_path(@question.test) %>
  </div>
</div>

app/views/admin/questions/show.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-8">
    <h1><%= @question.test.title %> <%= t('.question') %></h1>

    <p>
      <%= @question.body %><br>
      <%= link_to t('.edit'), edit_admin_question_path(@question) %><br>
    </p>

    <%= link_to t('.new_answer'), new_admin_question_answer_path(@question) %>

    <h2><%= t('.answers') %></h2>

    <%= render @question.answers %>

    <%= link_to t('.back'), admin_test_path(@question.test) %>
  </div>
</div>